services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env.development

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:${API_WORKDIR:-/app}
    ports:
      - "${API_PORT:-3000}:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:${DB_PASSWORD}@db:5432/${POSTGRES_DB}
      RAILS_ENV: ${RAILS_ENV:-development}
    env_file:
      - .env.development
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    volumes:
      - ./front/app:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - VITE_API_URL=${API_URL:-http://localhost:3000}
    env_file:
      - .env.development
    depends_on:
      - api
    user: "node"

volumes:
  postgres_data: