services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env.development

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:${API_WORKDIR}
      - rails_cache:${API_WORKDIR}/tmp/cache
      - rails_bootsnap:${API_WORKDIR}/tmp/bootsnap
    ports:
      - "${API_PORT}:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:${DB_PASSWORD}@db:5432/${POSTGRES_DB}
      RAILS_ENV: ${RAILS_ENV:-development}
    env_file:
      - .env.development
    command: >
      bash -c "
        bundle install &&
        rm -f tmp/pids/server.pid &&
        bundle exec rails db:create db:migrate &&
        bundle exec rails server -b 0.0.0.0
      "

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    volumes:
      - ./front/app:${FRONT_WORKDIR}
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - VITE_API_URL=${API_URL}
    env_file:
      - .env.development
    depends_on:
      - api

volumes:
  postgres_data:
  rails_cache:
  rails_bootsnap:
  # bundle_path:
  # api_storage: