services:
  db-test:
    image: postgres:14
    environment:
      POSTGRES_DB: osakana_calendar_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_secure_password

  api-test:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/app
    environment:
      DB_HOST: db-test
      POSTGRES_DB: osakana_calendar_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_secure_password
      RAILS_ENV: test
      ALLOWED_ORIGINS: http://localhost:5173
      YOUTUBE_API_KEY: "test_api_key"
    depends_on:
      - db-test
    command: >
      bash -c "
        bundle install &&
        bundle exec rails db:create db:migrate RAILS_ENV=test &&
        bundle exec rails test
      "

  frontend-test:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    volumes:
      - ./front/app:/app
      - /app/node_modules
    environment:
      NODE_ENV: test
      CI: true
      VITE_YOUTUBE_API_KEY: "test_api_key"
    command: >
      sh -c "
        npm run lint && 
        npm run test run
      "
