services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RAILS_ENV: ${RAILS_ENV}
      CORS_ORIGINS: ${CORS_ORIGINS}
      RAILS_DEVELOPMENT_HOSTS: ${RAILS_DEVELOPMENT_HOSTS}
      VITE_YOUTUBE_API_KEY: ${VITE_YOUTUBE_API_KEY}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
    env_file:
      - .env.development
    depends_on:
      - db
    command: >
      bash -c "
        rm -f tmp/pids/server.pid &&
        bundle exec rails db:migrate &&
        bundle exec rails db:seed &&
        bundle exec rails server -b 0.0.0.0
      "

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    volumes:
      - ./front/app:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: ${NODE_ENV}
      VITE_API_URL: ${VITE_API_URL}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
      VITE_FRONT_URL: ${VITE_FRONT_URL}
    env_file:
      - .env.development
    depends_on:
      - api

volumes:
  postgres_data:

# docker-compose --env-file .env.development up --build