services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env.development

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:${API_WORKDIR:-/app}
      - rails_cache:${API_WORKDIR:-/app}/tmp/cache
      - rails_bootsnap:${API_WORKDIR:-/app}/tmp/bootsnap
      - storage:${API_WORKDIR:-/app}/storage
    ports:
      - "${API_PORT:-3000}:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${DB_PASSWORD}@db:5432/${POSTGRES_DB}
      RAILS_ENV: ${RAILS_ENV:-development}
      RAILS_DEVELOPMENT_HOSTS: api,localhost,0.0.0.0
    env_file:
      - .env.development
    command: >
      bash -c "
        bundle install &&
        rm -f tmp/pids/server.pid &&
        bundle exec rails db:create db:migrate &&
        bundle exec rails server -b 0.0.0.0
      "

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    volumes:
      - ./front/app:${FRONT_WORKDIR:-/app}
      - /app/node_modules
    ports:
      - "${FRONT_PORT:-5173}:5173"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      VITE_API_URL: ${VITE_API_URL:-http://localhost:3000}
    env_file:
      - .env.development
    depends_on:
      - api

volumes:
  postgres_data:
  rails_cache:
  rails_bootsnap:
  storage: