services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: osakana_calendar_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_secure_password
    ports:
      - "5432:5432"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:your_secure_password@db:5432/osakana_calendar_db
      RAILS_ENV: development
      CORS_ORIGINS: http://localhost:5173
    depends_on:
      - db
    command: >
      bash -c "
      rm -f tmp/pids/server.pid &&
      bundle exec rails db:migrate &&
      bundle exec rails db:seed &&
      bundle exec rails server -b 0.0.0.0
      "

  api-test:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/app
    environment:
      DATABASE_URL: postgresql://postgres:your_secure_password@db:5432/osakana_calendar_test
      RAILS_ENV: test
      CORS_ORIGINS: http://localhost:5173
    depends_on:
      - db
    command: >
      bash -c "
      rm -f tmp/pids/server.pid &&
      bundle exec rails db:migrate RAILS_ENV=test &&
      bundle exec rails db:seed RAILS_ENV=test &&
      bundle exec rails test &&
      bundle exec rails server -b 0.0.0.0
      "

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    volumes:
      - ./front/app:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:3000
    depends_on:
      - api

  frontend-test:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    volumes:
      - ./front/app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
      - VITE_API_URL=http://api:3000
    command: npm test
    depends_on:
      - api-test

volumes:
  postgres_data:
