FROM node:20-alpine

WORKDIR /app

# package.jsonのパス
COPY app/package*.json ./
RUN npm install

# 開発サーバー用の設定
ENV NODE_ENV=development
EXPOSE 5173

# Vite開発サーバーを直接起動
CMD ["npm", "run", "dev", "--", "--host"]