FROM ruby:3.3.4-slim

# 必要な依存関係のインストール
RUN apt-get update -qq && \
    apt-get install -y build-essential libpq-dev nodejs && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# 開発用のGem インストール
COPY Gemfile* ./
RUN bundle install

# アプリケーションコードは volumeでマウント

# 開発サーバー起動
CMD ["rails", "server", "-b", "0.0.0.0"]