name: Deploy to Heroku

on:
  push:
    branches: [ main ]
    paths:
      - 'api/**'
      - 'front/**'
      - '.github/workflows/**'
      - 'docker-compose*.yml'

jobs:
  test:
    uses: ./.github/workflows/pr-test.yml
    secrets:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      POSTGRES_TEST_PASSWORD: ${{ secrets.POSTGRES_TEST_PASSWORD }}

  deploy-backend:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_BACKEND_APP }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
          appdir: "api"
        env:
          HD_RAILS_ENV: production
          HD_RAILS_SERVE_STATIC_FILES: enabled
          HD_RAILS_LOG_TO_STDOUT: enabled

      - name: Database migration
        if: success()
        run: |
          heroku run --app ${{ secrets.HEROKU_BACKEND_APP }} 'rails db:migrate'

  deploy-frontend:
    needs: deploy-backend
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_FRONTEND_APP }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
          appdir: "front"
        env:
          HD_NODE_ENV: production
          HD_VITE_API_URL: ${{ secrets.VITE_API_URL }}
